
CREATE SCHEMA IF NOT EXISTS sonarServicos;
use sonarServicos;

CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NM_CLIENTE VARCHAR(80),
	NR_CNPJ_CPF VARCHAR(14),
	NM_ENDERECO VARCHAR(255),
	NR_TEL_CEL VARCHAR(15),
	NR_TEL_COM VARCHAR(15),
	NR_TEL_RES VARCHAR(15),
	NM_EMAIL_CLI VARCHAR(100)
);

CREATE INDEX ID_DOC
ON CLIENTE (NR_CNPJ_CPF);

CREATE TABLE CLIENTE_PRESTADOR (
    ID_CLI_PRESTADOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
	DT_CLI_PRESTADOR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE INDEX IDX_PRESTADOR
ON CLIENTE_PRESTADOR (ID_CLI_PRESTADOR);

CREATE TABLE SERVICO(
	ID_SERVICO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NM_SERVICO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SERVICO_PRESTADOR (
  ID_CLI_PRESTADOR INT NOT NULL,
  ID_SERVICO INT NOT NULL,
  VL_ORCAMENTO DECIMAL(7,2) NULL,
  PRIMARY KEY (ID_CLI_PRESTADOR, ID_SERVICO),
  INDEX IDX_SERVICO_PREST (ID_SERVICO ASC),
  INDEX IDX_SERV_PRESTADOR (ID_CLI_PRESTADOR ASC),
  CONSTRAINT FK_SERVICO_PRESTADOR
    FOREIGN KEY (ID_CLI_PRESTADOR)
    REFERENCES CLIENTE_PRESTADOR (ID_CLI_PRESTADOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_SERVICO_PRESTADO
    FOREIGN KEY (ID_SERVICO)
    REFERENCES SERVICO (ID_SERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE INTERESSE(
  ID_CLIENTE INT NOT NULL,
  ID_CLI_PRESTADOR INT NOT NULL,
  ID_SERVICO INT NOT NULL,
  DT_INTERESSE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_CLIENTE, ID_CLI_PRESTADOR, ID_SERVICO),
  INDEX IDX_PRESTADOR_INTERESSE (ID_CLI_PRESTADOR ASC, ID_SERVICO ASC),
  INDEX IDX_CLIENTE_INTERESSADO (ID_CLIENTE ASC),
  CONSTRAINT FK_CLIENTE_INTERESSADO
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_PRESTADOR_INTERESSANTE
    FOREIGN KEY (ID_CLI_PRESTADOR , ID_SERVICO)
    REFERENCES SERVICO_PRESTADOR (ID_CLI_PRESTADOR , ID_SERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE AVALIACAO(
	ID_RECLAMACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	ID_CLIENTE INT NOT NULL, 
	ID_CLI_PRESTADOR INT NOT NULL, 
	AVALIACAO INT NOT NULL,
	RECLAMACAO VARCHAR(255),
	RESPOSTA VARCHAR(255),
	CONSTRAINT FK_AVAL_CLIENTE 
	FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(ID_CLIENTE)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	CONSTRAINT FK_AVAL_CLI_PRESTADOR 
	FOREIGN KEY (ID_CLI_PRESTADOR)
	REFERENCES CLIENTE_PRESTADOR(ID_CLI_PRESTADOR)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

	CREATE INDEX IDX_RECLAMACAO
	ON AVALIACAO(ID_CLI_PRESTADOR);

CREATE TABLE CONSULTA(

	ID_CONSULTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
	ID_SERVICO INT NOT NULL,
	NM_END_CONSULTA VARCHAR(14) NOT NULL,
	DT_CONSULTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_CLI_CONSULTA
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID_CLIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT FK_SER_CONSULTA
	FOREIGN KEY (ID_SERVICO)
	REFERENCES SERVICO(ID_SERVICO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);
-- CASO DE TESTES

 INSERT INTO CLIENTE(NM_CLIENTE, NR_CNPJ_CPF, NM_ENDERECO, NR_TEL_CEL, NR_TEL_COM,NR_TEL_RES, NM_EMAIL_CLI) VALUES ('Teste1 de teste testando', '99999999999', 'Rua da casa do teste1, 45 - bairro nobre - itaocara',  '5521999999999', '552123456788','552199999999', 'teste1@gmail.com');
 INSERT INTO CLIENTE(NM_CLIENTE, NR_CNPJ_CPF, NM_ENDERECO, NR_TEL_CEL, NR_TEL_COM,NR_TEL_RES, NM_EMAIL_CLI) VALUES ('Teste2 da silva teste', '99999999990', 'Rua da casa do teste1, 45 - bairro nobre - itaocara',  '5521999999998', '552123456789','552199999998', 'teste2@gmail.com');
 INSERT INTO  CLIENTE_PRESTADOR(ID_CLIENTE) VALUES (1);
 INSERT INTO CLIENTE_PRESTADOR(ID_CLIENTE) VALUES (2);
 INSERT INTO SERVICO(NM_SERVICO) VALUES ('Desenvolvimento de sistemas');
 INSERT INTO SERVICO(NM_SERVICO) VALUES ('Manutenção de computadores');
 INSERT INTO SERVICO_PRESTADOR   VALUES (1,1, 80.00);


 INSERT INTO SERVICO_PRESTADOR   VALUES (1,2, 100.00);
 INSERT INTO SERVICO_PRESTADOR   VALUES (2,1, 120.00);
 INSERT INTO SERVICO_PRESTADOR   VALUES (2,2, 50.00);
 INSERT INTO INTERESSE(ID_CLIENTE,ID_CLI_PRESTADOR, ID_SERVICO)  VALUES (1,2,2);
 INSERT INTO INTERESSE(ID_CLIENTE,ID_CLI_PRESTADOR, ID_SERVICO)  VALUES (2,1,1);

 INSERT INTO AVALIACAO(ID_CLIENTE, ID_CLI_PRESTADOR, AVALIACAO, RECLAMACAO) VALUES (1, 2, 5, 'Poderia ter sido melhor, mas foi bom');
 UPDATE AVALIACAO
 SET RESPOSTA='A excelência é nosso objetivo. Esperamos novos contatos'
 WHERE ID_RECLAMACAO = 1;
  
SELECT ClienteServico AS 'Cliente', PrestadorServico as 'Profissional', NM_SERVICO AS 'Serviço Buscado'
FROM (
	  SELECT s.NM_SERVICO, i.ID_CLI_PRESTADOR, i.ID_CLIENTE 
	  FROM INTERESSE i JOIN SERVICO s ON s.ID_SERVICO = i.ID_SERVICO
      ) AS Servico 
      
	  JOIN (
		SELECT u.NM_CLIENTE AS PrestadorServico, i.ID_CLI_PRESTADOR AS ID_CLI_PRESTADOR 
		FROM CLIENTE u JOIN INTERESSE i ON u.ID_CLIENTE = i.ID_CLI_PRESTADOR
	  ) AS Prestador 
	
		ON Servico.ID_CLI_PRESTADOR = Prestador.ID_CLI_PRESTADOR 
        
JOIN (

	SELECT u.NM_CLIENTE AS ClienteServico, i.ID_CLIENTE FROM CLIENTE u JOIN INTERESSE i ON u.ID_CLIENTE = i.ID_CLIENTE
    ) AS Cliente 
ON Cliente.ID_CLIENTE = Servico.ID_CLIENTE;
