DROP SCHEMA sonarServicos;
CREATE SCHEMA IF NOT EXISTS sonarServicos;
use sonarServicos;

CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NM_CLIENTE VARCHAR(80),
	NR_CNPJ_CPF VARCHAR(14),
	NM_ENDERECO VARCHAR(255),
	NR_TEL_CEL VARCHAR(15),
	NR_TEL_COM VARCHAR(15),
	NR_TEL_RES VARCHAR(15),
	NM_EMAIL_CLI VARCHAR(100),
	DT_CLIENTE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ID_DOC
ON CLIENTE (NR_CNPJ_CPF);

CREATE TABLE CLIENTE_PRESTADOR (
    ID_CLI_PRESTADOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
	DT_CLI_PRESTADOR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE INDEX IDX_PRESTADOR
ON CLIENTE_PRESTADOR (ID_CLI_PRESTADOR);

CREATE TABLE SERVICO(
	ID_SERVICO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NM_SERVICO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SERVICO_PRESTADOR (  
  ID_CLI_PRESTADOR INT NOT NULL,
  ID_SERVICO INT NOT NULL,
  VL_ORCAMENTO DECIMAL(7,2) NULL,
  PRIMARY KEY(ID_CLI_PRESTADOR, ID_SERVICO),
  CONSTRAINT FK_SERVICO_PRESTADOR
    FOREIGN KEY (ID_CLI_PRESTADOR)
    REFERENCES CLIENTE_PRESTADOR (ID_CLI_PRESTADOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_SERVICO_PRESTADO
    FOREIGN KEY (ID_SERVICO)
    REFERENCES SERVICO (ID_SERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE INTERESSE(  
  ID_INTERESSE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_CLI_PRESTADOR INT NOT NULL,
  ID_CLIENTE INT NOT NULL,  
  ID_SERVICO INT NOT NULL,
  DT_INTERESSE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_INT_PRESTADOR
  FOREIGN KEY (ID_CLI_PRESTADOR, ID_SERVICO)
  REFERENCES SERVICO_PRESTADOR (ID_CLI_PRESTADOR, ID_SERVICO)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT FK_INT_CLIENTE
  FOREIGN KEY (ID_CLIENTE)
  REFERENCES CLIENTE(ID_CLIENTE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT FK_INT_SERVICO
  FOREIGN KEY (ID_SERVICO)
  REFERENCES SERVICO_PRESTADOR(ID_SERVICO)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
  );
  
  CREATE INDEX IDX_INTERESSE
  ON INTERESSE (ID_INTERESSE);


CREATE TABLE AVALIACAO(
	ID_AVALIACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 	
	ID_INTERESSE INT NOT NULL,
	NR_AVALIACAO INT NOT NULL,
	NM_COMENTARIO VARCHAR(255),
	NM_RESPOSTA VARCHAR(255),
	DT_AVALIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AVAL_INTERESSE
    FOREIGN KEY (ID_INTERESSE)
    REFERENCES INTERESSE(ID_INTERESSE));

	CREATE INDEX IDX_AVALIACAO
	ON AVALIACAO(ID_AVALIACAO);

CREATE TABLE CONSULTA(

	ID_CONSULTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
	ID_SERVICO INT NOT NULL,
	NM_END_CONSULTA VARCHAR(14) NOT NULL,
	DT_CONSULTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_CLI_CONSULTA
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID_CLIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT FK_SER_CONSULTA
	FOREIGN KEY (ID_SERVICO)
	REFERENCES SERVICO(ID_SERVICO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);
    
    
 INSERT INTO CLIENTE(NM_CLIENTE, NR_CNPJ_CPF, NM_ENDERECO, NR_TEL_CEL, NR_TEL_COM,NR_TEL_RES, NM_EMAIL_CLI) VALUES ('Teste1 de teste testando', '99999999999', 'Rua da casa do teste1, 45 - bairro nobre - itaocara',  '5521999999999', '552123456788','552199999999', 'teste1@gmail.com');
 INSERT INTO CLIENTE(NM_CLIENTE, NR_CNPJ_CPF, NM_ENDERECO, NR_TEL_CEL, NR_TEL_COM,NR_TEL_RES, NM_EMAIL_CLI) VALUES ('Teste2 da silva teste', '99999999990', 'Rua da casa do teste1, 45 - bairro nobre - itaocara',  '5521999999998', '552123456789','552199999998', 'teste2@gmail.com');
 INSERT INTO  CLIENTE_PRESTADOR(ID_CLIENTE) VALUES (1);
 INSERT INTO CLIENTE_PRESTADOR(ID_CLIENTE) VALUES (2);
 INSERT INTO SERVICO(NM_SERVICO) VALUES ('Desenvolvimento de sistemas');
 INSERT INTO SERVICO(NM_SERVICO) VALUES ('Manutenção de computadores');
 INSERT INTO SERVICO_PRESTADOR (ID_CLI_PRESTADOR, ID_SERVICO, VL_ORCAMENTO)  VALUES (1,1, 80.00);
 INSERT INTO SERVICO_PRESTADOR (ID_CLI_PRESTADOR, ID_SERVICO, VL_ORCAMENTO)  VALUES (1,2, 100.00);
 INSERT INTO SERVICO_PRESTADOR (ID_CLI_PRESTADOR, ID_SERVICO, VL_ORCAMENTO) VALUES (2,1, 120.00);
 INSERT INTO SERVICO_PRESTADOR (ID_CLI_PRESTADOR, ID_SERVICO, VL_ORCAMENTO) VALUES (2,2, 50.00);
 INSERT INTO INTERESSE(ID_CLIENTE,ID_CLI_PRESTADOR, ID_SERVICO)  VALUES (2,1,2);
 INSERT INTO INTERESSE(ID_CLIENTE,ID_CLI_PRESTADOR, ID_SERVICO) VALUES (1,2,1);
 INSERT INTO AVALIACAO(ID_INTERESSE, NR_AVALIACAO, NM_COMENTARIO) VALUES (2, 5, 'Poderia ter sido melhor, mas foi bom');
 UPDATE AVALIACAO
 SET NM_RESPOSTA='A excelência é nosso objetivo. Esperamos novos contatos'
 WHERE ID_AVALIACAO = 1;
 INSERT INTO AVALIACAO(ID_INTERESSE, NR_AVALIACAO, NM_COMENTARIO) VALUES (1, 3, 'Meh');
 UPDATE AVALIACAO
 SET NM_RESPOSTA='Cliente Chato, Babaca da porra'
 WHERE ID_AVALIACAO = 2;
 
 
 SELECT * FROM INTERESSE i, AVALIACAO a, CLIENTE c WHERE a.ID_INTERESSE = i.ID_INTERESSE AND i.ID_CLIENTE = c.ID_CLIENTE;
 
