USE [sonarServicos]
GO

DROP TABLE LOGIN, INTERESSE, PRESTADOR_SERVICO, SERVICO, CLIENTE;

CREATE TABLE CLIENTE(

	ID_CLIENTE INT NOT NULL PRIMARY KEY IDENTITY,
	NM_CLIENTE VARCHAR(80) NOT NULL,
	NR_CNPJ_CPF VARCHAR(14) NOT NULL,
	NM_ENDERECO VARCHAR(255) NOT NULL,
	NR_TEL_CEL VARCHAR(15),
	NR_TEL_COM VARCHAR(15),
	NR_TEL_RES VARCHAR(15),	
	DT_CLIENTE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE SERVICO(
	
	ID_SERVICO INT NOT NULL PRIMARY KEY IDENTITY,
	NM_SERVICO VARCHAR(100) NOT NULL

);



CREATE TABLE PRESTADOR_SERVICO(

	ID_PRESTADOR INT NOT NULL,
	ID_SERVICO INT NOT NULL,
	NR_ORCAMENTO DECIMAL(7,2) NOT NULL DEFAULT 0.00,
	DT_PRESTADOR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID_PRESTADOR, ID_SERVICO),
	CONSTRAINT FK_CLI_PRESTADOR
	FOREIGN KEY (ID_PRESTADOR)
	REFERENCES CLIENTE (ID_CLIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT FK_SER_PRESTADOR
	FOREIGN KEY (ID_SERVICO)
	REFERENCES SERVICO (ID_SERVICO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

);


CREATE TABLE INTERESSE(
	
	ID_PRESTADOR INT NOT NULL,
	ID_SERVICO INT NOT NULL,
	ID_CLIENTE INT,	
	DT_INTERESSE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	NM_END_INTERESSE VARCHAR(256) NOT NULL,
	NR_AVALIACAO INT NOT NULL DEFAULT 0,
	NM_COMENTARIO VARCHAR(256),
	NM_RESPOSTA VARCHAR(256),
	DT_AVALIACAO DATETIME,
	PRIMARY KEY (ID_PRESTADOR, ID_SERVICO),
	CONSTRAINT FK_CLI_INTERSSE
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT FK_SER_INTERESSE
	FOREIGN KEY (ID_PRESTADOR, ID_SERVICO)
	REFERENCES PRESTADOR_SERVICO(ID_PRESTADOR, ID_SERVICO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
    );

CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL IDENTITY,
	NM_EMAIL VARCHAR(64) NOT NULL,
	NM_USUARIO VARCHAR(32) NOT NULL,
	NM_SENHA VARCHAR(32) NOT NULL,
	NM_HASH VARCHAR(70),
	ID_CLIENTE INT,
	CONSTRAINT FK_USUARIO_CLIENTE
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID_CLIENTE)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
);

-- Criação de Índices

CREATE INDEX IDX_INTERESSE
ON INTERESSE(NR_AVALIACAO);

CREATE INDEX IDX_CLI_PREST
ON PRESTADOR_SERVICO(ID_PRESTADOR, ID_SERVICO);

CREATE INDEX IDX_USUARIO
ON USUARIO(NM_USUARIO);

CREATE INDEX IDX_HASH
ON USUARIO(NM_HASH)

CREATE INDEX IDX_CLIENTE_EMAIL
ON USUARIO (NM_EMAIL);

CREATE INDEX IDX_NM_SERVICO
ON SERVICO(NM_SERVICO);

CREATE INDEX IDX_CPF_CNPJ
ON CLIENTE(NR_CNPJ_CPF);

CREATE INDEX IDX_CLIENTE_ENDERECO
ON CLIENTE (NM_ENDERECO);


-- Casos básicos para teste

INSERT INTO SERVICO (NM_SERVICO) VALUES ('Borracheiro');
INSERT INTO SERVICO (NM_SERVICO) VALUES ('Mecânico');

INSERT INTO USUARIO(NM_EMAIL, NM_USUARIO, NM_SENHA) VALUES ('zedopneu@gmail.com', 'zedopneu', 'c7848cabe6832b909a8ae7474711d40e');
INSERT INTO USUARIO(NM_EMAIL, NM_USUARIO, NM_SENHA) VALUES ('zedachave@gmail.com', 'zedachave', 'fd5f9c2163c102ffd224be40cf706c8a');
