USE [sonarServicos]
GO

CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL IDENTITY PRIMARY KEY,
	NM_USUARIO VARCHAR(80),
	NR_CNPJ_CPF VARCHAR(14),
	NM_ENDERECO VARCHAR(255),
	NR_TEL_CEL VARCHAR(15),
	NR_TEL_COM VARCHAR(15),
	NR_TEL_RES VARCHAR(15),
	NM_EMAIL_USU VARCHAR(100)
)

CREATE INDEX ID_DOC
ON USUARIO (NR_CNPJ_CPF)

CREATE TABLE USUARIO_PRESTADOR (
    ID_USU_PRESTADOR INT NOT NULL IDENTITY PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
);

CREATE INDEX IDX_PRESTADOR
ON USUARIO_PRESTADOR (ID_USU_PRESTADOR)

CREATE TABLE SERVICO(
	ID_SERVICO INT NOT NULL IDENTITY PRIMARY KEY,
	NM_SERVICO VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE SERVICO_PRESTADOR (
  ID_USU_PRESTADOR INT NOT NULL,
  ID_SERVICO INT NOT NULL,
  VL_ORCAMENTO DECIMAL(7,2) NULL,
  PRIMARY KEY (ID_USU_PRESTADOR, ID_SERVICO),
  INDEX IDX_SERVICO_PREST (ID_SERVICO ASC),
  INDEX IDX_SERV_PRESTADOR (ID_USU_PRESTADOR ASC),
  CONSTRAINT FK_SERVICO_PRESTADOR
    FOREIGN KEY (ID_USU_PRESTADOR)
    REFERENCES USUARIO_PRESTADOR (ID_USU_PRESTADOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_SERVICO_PRESTADO
    FOREIGN KEY (ID_SERVICO)
    REFERENCES SERVICO (ID_SERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE INTERESSE(
  ID_USUARIO INT NOT NULL,
  ID_USU_PRESTADOR INT NOT NULL,
  ID_SERVICO INT NOT NULL,
  PRIMARY KEY (ID_USUARIO, ID_USU_PRESTADOR, ID_SERVICO),
  INDEX IDX_PRESTADOR_INTERESSE (ID_USU_PRESTADOR ASC, ID_SERVICO ASC),
  INDEX IDX_USUARIO_INTERESSADO (ID_USUARIO ASC),
  CONSTRAINT FK_USUARIO_INTERESSADO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_PRESTADOR_INTERESSANTE
    FOREIGN KEY (ID_USU_PRESTADOR , ID_SERVICO)
    REFERENCES SERVICO_PRESTADOR (ID_USU_PRESTADOR , ID_SERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


USE [sonarServicos]
GO

DROP TABLE AVALIACAO


CREATE TABLE AVALIACAO(
	ID_RECLAMACAO INT NOT NULL PRIMARY KEY IDENTITY, 
	ID_USUARIO INT NOT NULL, 
	ID_USU_PRESTADOR INT NOT NULL, 
	AVALIACAO INT NOT NULL,
	RECLAMACAO VARCHAR(255),
	RESPOSTA VARCHAR(255),
	CONSTRAINT FK_AVAL_USUARIO 
	FOREIGN KEY (ID_USUARIO) 
	REFERENCES USUARIO(ID_USUARIO)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
	CONSTRAINT FK_AVAL_USU_PRESTADOR 
	FOREIGN KEY (ID_USU_PRESTADOR)
	REFERENCES USUARIO_PRESTADOR(ID_USU_PRESTADOR)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

	CREATE INDEX IDX_RECLAMACAO
	ON AVALIACAO(ID_USU_PRESTADOR);

-- CASO DE TESTES

 INSERT INTO USUARIO(NM_USUARIO, NR_CNPJ_CPF, NM_ENDERECO, NR_TEL_CEL, NR_TEL_COM,NR_TEL_RES, NM_EMAIL_USU) VALUES ('Teste1 de teste testando', '99999999999', 'Rua da casa do teste1, 45 - bairro nobre - itaocara',  '5521999999999', '552123456788','552199999999', 'teste1@gmail.com');
 INSERT INTO USUARIO(NM_USUARIO, NR_CNPJ_CPF, NM_ENDERECO, NR_TEL_CEL, NR_TEL_COM,NR_TEL_RES, NM_EMAIL_USU) VALUES ('Teste2 da silva teste', '99999999990', 'Rua da casa do teste1, 45 - bairro nobre - itaocara',  '5521999999998', '552123456789','552199999998', 'teste2@gmail.com');
 INSERT INTO  USUARIO_PRESTADOR(ID_USUARIO) VALUES (1);
 INSERT INTO USUARIO_PRESTADOR(ID_USUARIO) VALUES (2);
 INSERT INTO SERVICO(NM_SERVICO) VALUES ('Desenvolvimento de sistemas');
 INSERT INTO SERVICO(NM_SERVICO) VALUES ('Manutenção de computadores');
 INSERT INTO SERVICO_PRESTADOR   VALUES (1,1, 80.00);


 INSERT INTO SERVICO_PRESTADOR   VALUES (1,2, 100.00);
 INSERT INTO SERVICO_PRESTADOR   VALUES (2,1, 120.00);
 INSERT INTO SERVICO_PRESTADOR   VALUES (2,2, 50.00);
 INSERT INTO INTERESSE(ID_USUARIO,ID_USU_PRESTADOR, ID_SERVICO)  VALUES (1,2,2);
 INSERT INTO INTERESSE(ID_USUARIO,ID_USU_PRESTADOR, ID_SERVICO)  VALUES (2,1,1);

 INSERT INTO AVALIACAO(ID_USUARIO, ID_USU_PRESTADOR, AVALIACAO, RECLAMACAO) VALUES (1, 2, 5, 'Poderia ter sido melhor, mas foi bom');
 UPDATE AVALIACAO
 SET RESPOSTA='A excelência é nosso objetivo. Esperamos novos contatos'
 WHERE ID_RECLAMACAO = 1;
  
SELECT ClienteServico AS 'Cliente', PrestadorServico as 'Profissional', NM_SERVICO AS 'Serviço Buscado'
FROM (
	  SELECT s.NM_SERVICO, i.ID_USU_PRESTADOR, i.ID_USUARIO 
	  FROM INTERESSE i JOIN SERVICO s ON s.ID_SERVICO = i.ID_SERVICO
      ) AS Servico 
      
	  JOIN (
		SELECT u.NM_USUARIO AS PrestadorServico, i.ID_USU_PRESTADOR AS ID_USU_PRESTADOR 
		FROM USUARIO u JOIN INTERESSE i ON u.ID_USUARIO = i.ID_USU_PRESTADOR
	  ) AS Prestador 
	
		ON Servico.ID_USU_PRESTADOR = Prestador.ID_USU_PRESTADOR 
        
JOIN (

	SELECT u.NM_USUARIO AS ClienteServico, i.ID_USUARIO FROM USUARIO u JOIN INTERESSE i ON u.ID_USUARIO = i.ID_USUARIO
    ) AS Cliente 
ON Cliente.ID_USUARIO = Servico.ID_USUARIO;
