--CREATE TABLE USUARIO(
--	ID_USUARIO INT NOT NULL IDENTITY PRIMARY KEY,
--	NM_USUARIO VARCHAR(80),
--	NR_CNPJ_CPF VARCHAR(14),
--	NM_ENDERECO VARCHAR(255),
--	NR_TEL_CEL VARCHAR(15),
--	NR_TEL_COM VARCHAR(15),
--	NR_TEL_RES VARCHAR(15),
--	NM_EMAIL_USU VARCHAR(100)
--)

--CREATE INDEX ID_DOC
--ON USUARIO (NR_CNPJ_CPF)

--CREATE TABLE USUARIO_SERVICO(
--	ID_USU_SERVICO INT NOT NULL IDENTITY PRIMARY KEY,
--	ID_USUARIO INT NOT NULL 
--)

--CREATE TABLE USUARIO_PRESTADOR (
--    ID_USU_PRESTADOR INT NOT NULL,
--    ID_USUARIO INT NOT NULL,
--    PRIMARY KEY (ID_USU_PRESTADOR),
--    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO)
--    REFERENCES USUARIO(ID_USUARIO)
--);

--CREATE INDEX IDX_PRESTADOR
--ON USUARIO_PRESTADOR (ID_USU_PRESTADOR)

--CREATE TABLE SERVICO(
--	ID_SERVICO INT NOT NULL IDENTITY PRIMARY KEY,
--	NM_SERVICO VARCHAR(100) NOT NULL
--)

--CREATE TABLE SERVICO_PRESTADOR (
--  ID_USU_PRESTADOR INT NOT NULL,
--  ID_SERVICO INT NOT NULL,
--  VL_ORCAMENTO DECIMAL(7,2) NULL,
--  PRIMARY KEY (ID_USU_PRESTADOR, ID_SERVICO),
--  INDEX IDX_SERVICO_PREST (ID_SERVICO ASC),
--  INDEX IDX_SERV_PRESTADOR (ID_USU_PRESTADOR ASC),
--  CONSTRAINT FK_SERVICO_PRESTADOR
--    FOREIGN KEY (ID_USU_PRESTADOR)
--    REFERENCES USUARIO_PRESTADOR (ID_USU_PRESTADOR)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT FK_SERVICO_PRESTADO
--    FOREIGN KEY (ID_SERVICO)
--    REFERENCES SERVICO (ID_SERVICO)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION);

--CREATE TABLE INTERESSE(
--  ID_USUARIO INT NOT NULL,
--  ID_USU_PRESTADOR INT NOT NULL,
--  ID_SERVICO INT NOT NULL,
--  PRIMARY KEY (ID_USUARIO, ID_USU_PRESTADOR, ID_SERVICO),
--  INDEX IDX_PRESTADOR_INTERESSE (ID_USU_PRESTADOR ASC, ID_SERVICO ASC),
--  INDEX IDX_USUARIO_INTERESSADO (ID_USUARIO ASC),
--  CONSTRAINT FK_USUARIO_INTERESSADO
--    FOREIGN KEY (ID_USUARIO)
--    REFERENCES USUARIO (ID_USUARIO)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT FK_PRESTADOR_INTERESSANTE
--    FOREIGN KEY (ID_USU_PRESTADOR , ID_SERVICO)
--    REFERENCES SERVICO_PRESTADOR (ID_USU_PRESTADOR , ID_SERVICO)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION);


INSERT INTO USUARIO(nomeUsuario, documentoUsuario, enderecoUsuario, celularUsuario, telefoneUsuario,comercialUsuario, emailUsuario) 
	   VALUES ("Teste1 de teste testando", "99999999999", "Rua da casa do teste1, 45 - bairro nobre - itaocara",  "5521999999999", "552123456788","552199999999", "teste1@gmail.com");
INSERT INTO USUARIO(nomeUsuario, documentoUsuario, enderecoUsuario, celularUsuario, telefoneUsuario,comercialUsuario, emailUsuario) 
	   VALUES ("Teste2 da silva teste", "99999999990", "Rua da casa do teste1, 45 - bairro nobre - itaocara",  "5521999999998", "552123456789","552199999998", "teste2@gmail.com");
INSERT INTO tblprestadorservico(idUsuario)
	   VALUES (1);
INSERT INTO tblprestadorservico(idUsuario)
	   VALUES (2);
INSERT INTO tblservico(nomeServico)
	   VALUES ("Desenvolvimento de sistemas");
INSERT INTO tblservico(nomeServico)
	   VALUES ("Manutenção de computadores");
INSERT INTO tblservicoprestador
	   VALUES (1,1, 80.00);
INSERT INTO tblservicoprestador
	   VALUES (1,2, 100.00);
INSERT INTO tblservicoprestador
	   VALUES (2,1, 120.00);
INSERT INTO tblservicoprestador
       VALUES (2,2, 50.00);
INSERT INTO tblinteresse(idUsuario,idPrestadorServico, idServico)
	   VALUES (1,2,2);
INSERT INTO tblinteresse(idUsuario,idPrestadorServico, idServico)
	   VALUES (2,1,1);
